# Generated by Django 2.0.5 on 2018-05-29 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vejoi', '0002_auto_20180529_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='responder_id',
            new_name='responder',
        ),
    ]
