# Generated by Django 2.0.5 on 2018-05-29 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vejoi', '0003_auto_20180529_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='responder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL),
        ),
    ]
