# Generated by Django 2.0.6 on 2018-06-02 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vejoi', '0004_auto_20180530_0729'),
        ('vejoi', '0004_auto_20180529_0951'),
    ]

    operations = [
    ]
