# Generated by Django 2.0.6 on 2018-06-05 02:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vejoi', '0005_merge_20180602_0516'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='date',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='Date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='name',
            field=models.CharField(default='', max_length=255, null=True, verbose_name='Name of asker'),
        ),
    ]
