# Generated by Django 2.0.6 on 2018-06-05 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vejoi', '0006_auto_20180605_0229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
