version: '3'

services:
    postgres:
        image: postgres
    web:
        build: .
        command: python3 manage.py runserver 0.0.0.0:80
        volumes:
            - .:/codebase
        ports:
            - "5000:80"
        depends_on:
            - postgres
    pgadmin:
        image: dpage/pgadmin4:latest
        ports:
            - "8000:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=vuductaiptit@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=ductai97
 